### PR TITLE
Introduce events.

### PR DESCRIPTION
**Pull request by henryouly**
This change should be a pure refactor using C# event. No functional changes and no changes to when the callbacks are executed.

@superkudo can you please test if this slows things down on Windows? This is similar to https://github.com/SeedV/SeedUnityVRKit/tree/henryouly-test-csharp-event. The difference here is that henryouly-test-csharp-event tries to revert things, but this change starts from a proven commit.

### CODE REVIEW

**Comment by superkudo** [comment]
OK

**Comment by henryouly** [comment]
(Rebased the change to main and fix wrong variable case)

**Comment by superkudo** [comment]
I test in my windows， It has slow things down too.  and have a error in  HandLandmarksController .
image

**Comment by superkudo** [comment]
https://github.com/SeedV/SeedUnityVRKit/blob/szf_eventbind_rollback_features/Assets/Scripts/Tracker/HolisticTracker.cs
This version is not slow things down. I test again.

**Comment by henryouly** [comment]
Maybe `eventArgs.value` can be `null` in the callbacks, and it needs to be checked before passing to `UpperBodyAnimator` / `HandLandmarksController`, or otherwise it would override any previous valid results.

Let me push another commit in this PR to see if that's the cause.

**Review by superkudo — APPROVED** [review]

**Comment by superkudo** [comment]
It was eventArgs.value null  cause the slow things down， the null value effect the frame.  There have no slow things down in this commit in  MAC and windows.  I send the test video in email

**Pull request merged**
